name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install OS deps
      shell: bash
      run: |
        sudo apt-get update \
          && DEBIAN_FRONTEND=noninteractive \
          sudo apt-get install \
            -y --no-install-recommends \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-lang-cyrillic

    - name: Build static
      env:
        BUILD_MODE: production
      shell: bash
      run: |
        npm install
        npm run export
        mv dist artifact
        echo "---\npermalink: /404.html\n---" > artifact/404.md

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pages
        path: artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: pages
        path: artifact.tar

    - name: Extract artifact
      shell: bash
      run: |
        mv artifact.tar site

    - name: Upload pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: "site/"

    - name: Deploy pages
      id: deployment
      uses: actions/deploy-pages@v1
